# Generated by Django 4.2.1 on 2025-04-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='man',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='man.category'),
        ),
        migrations.AddField(
            model_name='man',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuman', to='man.husband'),
        ),
        migrations.AddField(
            model_name='man',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='man.tagpost'),
        ),
        migrations.AddIndex(
            model_name='man',
            index=models.Index(fields=['-time_create'], name='man_man_time_cr_3b5135_idx'),
        ),
    ]
